server:
  port: 1010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_system
    username: developer
    password: supersecret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: staging
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload-directory: lms-uploads
  folder-temp: ./lms-temp/
  jwt-secret: libraryManagementSystemSecretKeyForJWTTokenGenerationMustBeLongEnoughForHS256Algorithm
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:8000

logging:
  level:
    com.sinaukoding.ecommerce: INFO

springdoc:
  api-docs:
    defaultModelsExpandDepth: -1
    docExpansion: none
    enabled: true
    tagsSorter: alpha
    operationsSorter: alpha